#!/usr/bin/env python3
"""Validate that a PR body conforms to the required structure.

Reads the PR body from stdin or the first positional argument.
Exits 0 when the body passes all checks, exits 1 with a message to stderr
when any check fails.

Checks performed:
  1. Required sections are present (configurable via --config).
  2. Test plan bullets use `- [ ]` or `- [x]` format and every bullet
     contains at least one backtick-enclosed executable command.
  3. No AI-tool watermark / auto-generation signature is present.

Usage:
  pr_body_structure.py [BODY_TEXT]
  pr_body_structure.py --config rules.json [BODY_TEXT]
  cat body.txt | pr_body_structure.py
  cat body.txt | pr_body_structure.py --config rules.json
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import List, Optional

# ---------------------------------------------------------------------------
# Default configuration
# ---------------------------------------------------------------------------

DEFAULT_SECTIONS = [
    "## Summary",
    "## Implementation notes",
    "## Test plan",
    "## Closes",
]

AI_WATERMARK_PATTERNS: List[str] = [
    r"Generated with Claude Code",
    r"Co-Authored-By:",
    r"This PR was created by",
    r"🤖\s*Generated with",
    r"Created with \[Cursor",
    r"Created with \[Windsurf",
    r"Created with \[Copilot",
    r"Created with \[Cline",
    r"Created with \[Devin",
    r"Created with \[Aider",
    r"Created with \[v0",
    r"Created with \[Replit",
    r"Created with \[Bolt",
    r"Created with \[Lovable",
    r"Created with \[Trae",
    r"Created with \[Coze",
    r"This change was automatically generated",
    r"auto-generated by",
    r"generated by AI",
]

# Regex for a Markdown checkbox bullet that contains at least one
# backtick-enclosed token (an executable command).
_TEST_BULLET_RE = re.compile(
    r"^\s*[-*+]\s+\[[ x]\]\s+.*`[^`]+`.*",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def die(msg: str) -> None:
    """Print *msg* to stderr, then raise SystemExit(1)."""
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_config(path: str) -> dict:
    """Load a JSON config file and return its contents as a dict."""
    try:
        raw = Path(path).read_text(encoding="utf-8")
    except OSError as exc:
        die(f"Cannot read config file '{path}': {exc}")
    try:
        cfg = json.loads(raw)
    except json.JSONDecodeError as exc:
        die(f"Invalid JSON in config file '{path}': {exc}")
    if not isinstance(cfg, dict):
        die(f"Config file '{path}' must contain a JSON object, got {type(cfg).__name__}")
    return cfg


def gather_body() -> str:
    """Return the PR body text from stdin (if piped) or the first CLI argument."""
    if not sys.stdin.isatty():
        return sys.stdin.read()
    if len(sys.argv) > 1:
        return sys.argv[1]
    die(
        "No PR body provided. Pipe the body via stdin or pass it as the"
        " first positional argument."
    )


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------

def check_sections(body: str, required: List[str]) -> None:
    """Verify that every required section heading appears in *body*."""
    missing = [s for s in required if s not in body]
    if missing:
        die(
            "Missing required section(s) in PR body: "
            + ", ".join(missing)
        )


def check_test_plan(body: str) -> None:
    """Validate the '## Test plan' section.

    Every line that looks like a checkbox bullet (`- [ ]` / `- [x]`)
    must contain at least one backtick-enclosed command.
    """
    # Locate the Test plan section.
    idx = body.find("## Test plan")
    if idx == -1:
        return  # absence is already reported by check_sections

    # Grab text from the heading to the next `## ` heading (or EOF).
    tail = body[idx + len("## Test plan"):]
    next_heading = re.search(r"^## ", tail, re.MULTILINE)
    section_text = tail[: next_heading.start()] if next_heading else tail

    # Find checkbox bullets.
    lines = section_text.splitlines()
    checkboxes = [ln for ln in lines if re.match(r"^\s*[-*+]\s+\[[ x]\]", ln)]

    if not checkboxes:
        die("Test plan must contain at least one checkbox bullet (`- [ ]` or `- [x]`).")

    bad: list[str] = []
    for ln in checkboxes:
        if not _TEST_BULLET_RE.match(ln):
            bad.append(ln.strip())

    if bad:
        die(
            "Test-plan bullets must include backtick-enclosed executable"
            " commands.  Offending lines:\n  "
            + "\n  ".join(bad)
        )


def check_watermarks(body: str) -> None:
    """Reject the PR body if any AI watermark pattern is found."""
    hits: list[str] = []
    for pattern in AI_WATERMARK_PATTERNS:
        if re.search(pattern, body):
            hits.append(pattern)
    if hits:
        die(
            "PR body contains AI-tool watermark(s)."
            " Please remove them before submitting.\n"
            "  Detected patterns:\n    "
            + "\n    ".join(hits)
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

HELP_TEXT = """\
usage: pr_body_structure.py [--config CONFIG] [BODY_TEXT]

Validate that a PR body conforms to the required structure.

Positional arguments:
  BODY_TEXT          PR body text to validate (reads from stdin if omitted).

Options:
  --config CONFIG    Path to a JSON config file that specifies custom
                     required sections.  Expected format:

                       {{ "sections": ["## Summary", "## Test plan", ...] }}

                     When omitted the default sections are used:
                       {DEFAULT}

  --help             Show this help message and exit.

Exit status:
  0   PR body is valid.
  1   PR body failed one or more checks (details are printed to stderr).
""".format(DEFAULT=", ".join(DEFAULT_SECTIONS))


def parse_args(argv: list[str]) -> tuple[Optional[str], Optional[str]]:
    """Return (body_text_or_None, config_path_or_None)."""
    config: Optional[str] = None
    body: Optional[str] = None
    args = argv[1:]  # skip program name
    i = 0
    while i < len(args):
        if args[i] == "--help":
            print(HELP_TEXT)
            raise SystemExit(0)
        elif args[i] == "--config":
            i += 1
            if i >= len(args):
                die("--config requires a path argument.")
            config = args[i]
        elif not args[i].startswith("-"):
            body = args[i]
        else:
            die(f"Unknown option: {args[i]}")
        i += 1
    return body, config


def main() -> None:
    body_arg, config_path = parse_args(sys.argv)

    # Resolve body text.
    if body_arg is not None:
        body = body_arg
    else:
        body = gather_body()

    body = body.strip()
    if not body:
        die("PR body is empty.  A non-empty body is required.")

    # Resolve required sections.
    if config_path is not None:
        cfg = load_config(config_path)
        sections: list[str] = cfg.get("sections", DEFAULT_SECTIONS)
        if not isinstance(sections, list) or not all(isinstance(s, str) for s in sections):
            die("Config 'sections' must be a list of strings.")
    else:
        sections = DEFAULT_SECTIONS

    # Run checks.
    check_sections(body, sections)
    check_test_plan(body)
    check_watermarks(body)

    print("OK: PR body passes all structure checks.")
    raise SystemExit(0)


if __name__ == "__main__":
    main()
