#!/usr/bin/env python3
"""Validate that a PR body conforms to the required structure.

Reads the PR body from stdin or the first positional argument.
Exits 0 when the body passes all checks, exits 1 with a message to stderr
when any check fails.

Checks performed:
  1. Required sections are present (configurable via --config).
  2. Required order: Summary → Implementation notes → Test plan.
  3. Test plan bullets use `- [ ]` or `- [x]` format and every bullet
     contains at least one backtick-enclosed executable command.
  4. Issue trailer follows the issue-first rule: final PRs close the issue;
     non-final PRs reference it without closing it.
  5. No AI-tool watermark / auto-generation signature is present.

Usage:
  pr_body_structure.py [BODY_TEXT]
  pr_body_structure.py --config rules.json [BODY_TEXT]
  cat body.txt | pr_body_structure.py
  cat body.txt | pr_body_structure.py --config rules.json
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import List, Optional

# ---------------------------------------------------------------------------
# Default configuration
# ---------------------------------------------------------------------------

DEFAULT_SECTIONS = [
    "## Summary",
    "## Implementation notes",
    "## Test plan",
]

SECTION_MARKER_BY_SECTION = {
    "## Summary": "<!-- dayu-harness:summary -->",
    "## Implementation notes": "<!-- dayu-harness:implementation-notes -->",
    "## Test plan": "<!-- dayu-harness:test-plan -->",
}

SECTION_HEADER_PATTERNS = {
    "## Summary": re.compile(r"^##\s*Summary\b", re.MULTILINE),
    "## Implementation notes": re.compile(r"^##\s*Implementation\s+notes\b", re.MULTILINE),
    "## Test plan": re.compile(r"^##\s*Test\s+plan\b", re.MULTILINE),
}

SECTION_MARKER_PATTERNS = {
    "## Summary": re.compile(r"<!--\s*dayu-harness:summary\s*-->"),
    "## Implementation notes": re.compile(r"<!--\s*dayu-harness:implementation-notes\s*-->"),
    "## Test plan": re.compile(r"<!--\s*dayu-harness:test-plan\s*-->"),
}

SECTION_BOUNDARY_RE = re.compile(
    r"^(?:##\s+.+|<!--\s*dayu-harness:(?:summary|implementation-notes|test-plan)\s*-->)",
    re.MULTILINE,
)

ISSUE_TRAILER_RE = re.compile(
    r"^\s*(?P<keyword>Closes|Fixes|Resolves|Refs|Part of)\s+#(?P<issue>\d+)\s*$",
    re.IGNORECASE | re.MULTILINE,
)

CLOSING_KEYWORDS = {"closes", "fixes", "resolves"}
NON_CLOSING_KEYWORDS = {"refs", "part of"}
FINAL_PR_RE = re.compile(r"^\s*Final PR:\s*(?P<value>yes|no|true|false)\s*$", re.IGNORECASE | re.MULTILINE)
FORBIDDEN_CLOSING_HEADING_RE = re.compile(r"^##\s*Closes\b", re.IGNORECASE | re.MULTILINE)

AI_WATERMARK_PATTERNS = [
    r"Generated with Claude",
    r"Generated with ChatGPT",
    r"Created with Claude",
    r"Generated with [Cc]laude",
    r"Co-Authored-By:",
    r"This PR was created by",
    r"🤖\s*Generated with",
    r"Created with \[Cursor",
    r"Created with \[Windsurf",
    r"Created with \[Copilot",
    r"Created with \[Cline",
    r"Created with \[Devin",
    r"Created with \[Aider",
    r"Created with \[v0",
    r"Created with \[Replit",
    r"Created with \[Bolt",
    r"Created with \[Lovable",
    r"Created with \[Trae",
    r"Created with \[Coze",
    r"This change was automatically generated",
    r"auto-generated by",
    r"generated by AI",
]

# Regex for a Markdown checkbox bullet that contains at least one
# backtick-enclosed token (an executable command).
_TEST_BULLET_RE = re.compile(
    r"^\s*[-*+]\s+\[[ x]\]\s+.*`[^`]+`.*",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def die(msg: str) -> None:
    """Print *msg* to stderr, then raise SystemExit(1)."""
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_config(path: str) -> dict:
    """Load a JSON config file and return its contents as a dict."""
    try:
        raw = Path(path).read_text(encoding="utf-8")
    except OSError as exc:
        die(f"Cannot read config file '{path}': {exc}")
    try:
        cfg = json.loads(raw)
    except json.JSONDecodeError as exc:
        die(f"Invalid JSON in config file '{path}': {exc}")
    if not isinstance(cfg, dict):
        die(f"Config file '{path}' must contain a JSON object, got {type(cfg).__name__}")
    return cfg


def gather_body() -> str:
    """Return the PR body text from stdin (if piped) or the first CLI argument."""
    if not sys.stdin.isatty():
        return sys.stdin.read()
    if len(sys.argv) > 1:
        return sys.argv[1]
    die(
        "No PR body provided. Pipe the body via stdin or pass it as the"
        " first positional argument."
    )


def normalize_keyword(value: str) -> str:
    return value.strip().lower()


def extract_issue_trailer(body: str) -> tuple[str, int] | None:
    matches = list(ISSUE_TRAILER_RE.finditer(body))
    if not matches:
        return None
    if len(matches) > 1:
        die("PR body must include exactly one issue trailer line.")
    match = matches[0]
    return normalize_keyword(match.group("keyword")), int(match.group("issue"))


def extract_final_pr(body: str) -> Optional[bool]:
    matches = list(FINAL_PR_RE.finditer(body))
    if not matches:
        return None
    if len(matches) > 1:
        die("PR body must include at most one 'Final PR: yes/no' line.")
    value = matches[0].group("value").lower()
    return value in {"yes", "true"}


def load_open_prs_from_file(path: str) -> list[dict]:
    data = load_config(path)
    prs = data.get("pulls", data.get("prs", data.get("items", [])))
    if not isinstance(prs, list):
        die(f"Open PRs fixture '{path}' must contain a pulls/prs/items array.")
    return [item for item in prs if isinstance(item, dict)]


def fetch_open_prs_via_api(repo: str, token: str) -> list[dict]:
    prs: list[dict] = []
    page = 1
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "User-Agent": "dayu-harness-pr-body",
    }
    while True:
        url = f"https://api.github.com/repos/{repo}/pulls?state=open&per_page=100&page={page}"
        request = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(request, timeout=20) as response:
            data = json.loads(response.read().decode("utf-8"))
        if not isinstance(data, list):
            die("GitHub API returned an unexpected open PRs payload.")
        if not data:
            break
        prs.extend(item for item in data if isinstance(item, dict))
        if len(data) < 100:
            break
        page += 1
    return prs


def fetch_open_prs_via_gh(repo: str) -> list[dict]:
    if shutil.which("gh") is None:
        return []
    proc = subprocess.run(
        ["gh", "api", f"repos/{repo}/pulls?state=open&per_page=100", "--paginate"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return []

    prs: list[dict] = []
    decoder = json.JSONDecoder()
    index = 0
    raw = proc.stdout
    while index < len(raw):
        while index < len(raw) and raw[index].isspace():
            index += 1
        if index >= len(raw):
            break
        page_data, index = decoder.raw_decode(raw, index)
        if isinstance(page_data, dict):
            prs.append(page_data)
        elif isinstance(page_data, list):
            prs.extend(item for item in page_data if isinstance(item, dict))
    return prs


def open_prs_for_issue(
    issue_number: int,
    current_pr_number: Optional[int],
    repo: Optional[str],
    token: Optional[str],
    open_prs_json: Optional[str],
) -> list[int]:
    if open_prs_json:
        prs = load_open_prs_from_file(open_prs_json)
    elif repo and token:
        prs = fetch_open_prs_via_api(repo, token)
    elif repo:
        prs = fetch_open_prs_via_gh(repo)
    else:
        return []

    matching: list[int] = []
    for item in prs:
        number = item.get("number")
        if not isinstance(number, int):
            continue
        if current_pr_number is not None and number == current_pr_number:
            continue
        body = str(item.get("body") or "")
        referenced_issues = {
            int(match.group("issue"))
            for match in ISSUE_TRAILER_RE.finditer(body)
        }
        if issue_number in referenced_issues:
            matching.append(number)
    return sorted(set(matching))


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def _consume_adjacent_same_section_tokens(body: str, section: str, pos: int) -> int:
    """Advance `pos` past immediately-adjacent same-section heading/marker pairs."""
    header_re = SECTION_HEADER_PATTERNS.get(section)
    marker_re = SECTION_MARKER_PATTERNS.get(section)

    while pos < len(body):
        # Allow optional whitespace between the section heading and marker variant.
        while pos < len(body) and body[pos].isspace():
            pos += 1

        if header_re is not None:
            header_match = header_re.match(body, pos)
            if header_match is not None:
                pos = header_match.end()
                continue

        if marker_re is not None:
            marker_match = marker_re.match(body, pos)
            if marker_match is not None:
                pos = marker_match.end()
                continue

        break

    return pos


def check_sections(body: str, required: List[str]) -> None:
    """Verify required sections appear and are in the configured order.

    A required section is satisfied by either its legacy H2 heading or the
    corresponding marker comment.
    """
    indices = {}
    for section in required:
        header_re = SECTION_HEADER_PATTERNS.get(section)
        marker_re = SECTION_MARKER_PATTERNS.get(section)

        matches = []
        if header_re is not None:
            matches.extend((m.start(), m.end()) for m in header_re.finditer(body))
        if marker_re is not None:
            matches.extend((m.start(), m.end()) for m in marker_re.finditer(body))
        if header_re is None and marker_re is None:
            literal_idx = body.find(section)
            if literal_idx != -1:
                matches.append((literal_idx, literal_idx + len(section)))

        idx = -1
        end = -1
        if matches:
            idx, end = min(matches, key=lambda item: item[0])
        if idx == -1:
            die(f"Missing required section in PR body: {section}")
        indices[section] = (idx, end)

    ordered = [indices[s][0] for s in required]
    if ordered != sorted(ordered):
        die("PR body sections must appear in order: " + " -> ".join(required))


def section_span(body: str, section: str) -> tuple[int, int]:
    """Return start and end positions for a section marker or heading."""
    header_re = SECTION_HEADER_PATTERNS.get(section)
    marker_re = SECTION_MARKER_PATTERNS.get(section)

    matches = []
    if header_re is not None:
        matches.extend((m.start(), m.end()) for m in header_re.finditer(body))
    if marker_re is not None:
        matches.extend((m.start(), m.end()) for m in marker_re.finditer(body))

    if not matches:
        return -1, -1

    start, end = min(matches, key=lambda item: item[0])
    return start, _consume_adjacent_same_section_tokens(body, section, end)


def check_closing_trailer(
    body: str,
    repo: Optional[str] = None,
    pr_number: Optional[int] = None,
    token: Optional[str] = None,
    open_prs_json: Optional[str] = None,
) -> None:
    """Verify that a closing trailer is present and no heading is used instead."""
    if FORBIDDEN_CLOSING_HEADING_RE.search(body):
        die("Do not use a '## Closes' heading in PR body. Use an inline trailer instead.")

    trailer = extract_issue_trailer(body)
    if trailer is None:
        die("PR body must include one trailer line: Closes #N / Fixes #N / Resolves #N / Refs #N / Part of #N.")

    keyword, issue_number = trailer
    final_pr = extract_final_pr(body)

    if final_pr is False and keyword not in NON_CLOSING_KEYWORDS:
        die("Non-final PRs must use a non-closing issue trailer: Refs #N or Part of #N.")

    if final_pr is True and keyword not in CLOSING_KEYWORDS:
        die("Final PRs must use a closing issue trailer: Closes #N / Fixes #N / Resolves #N.")

    if final_pr is None and keyword not in CLOSING_KEYWORDS:
        die("Non-closing issue trailers require an explicit 'Final PR: no' line.")

    if keyword in CLOSING_KEYWORDS:
        linked_open_prs = open_prs_for_issue(
            issue_number,
            pr_number,
            repo,
            token,
            open_prs_json,
        )
        if linked_open_prs:
            refs = ", ".join(f"#{number}" for number in linked_open_prs)
            die(
                "Closing issue trailer is not allowed while other open PRs reference "
                f"the same issue #{issue_number}: {refs}. Use 'Final PR: no' with "
                "'Refs #N' / 'Part of #N' until the last PR."
            )


def check_test_plan(body: str) -> None:
    """Validate the '## Test plan' section.

    Every line that looks like a checkbox bullet (`- [ ]` / `- [x]`)
    must contain at least one backtick-enclosed command.
    """
    idx, idx_end = section_span(body, "## Test plan")
    if idx == -1:
        return  # absence is already reported by check_sections

    # Grab text from the heading/marker to the next section boundary (or EOF).
    boundary = SECTION_BOUNDARY_RE.search(body, idx_end)
    section_text = body[idx_end:boundary.start()] if boundary else body[idx_end:]

    # Find checkbox bullets.
    lines = section_text.splitlines()
    checkboxes = [ln for ln in lines if re.match(r"^\s*[-*+]\s+\[[ x]\]", ln)]

    if not checkboxes:
        die("Test plan must contain at least one checkbox bullet (`- [ ]` or `- [x]`).")

    bad: list[str] = []
    for ln in checkboxes:
        if not _TEST_BULLET_RE.match(ln):
            bad.append(ln.strip())

    if bad:
        die(
            "Test-plan bullets must include backtick-enclosed executable"
            " commands.  Offending lines:\n  "
            + "\n  ".join(bad)
        )


def check_watermarks(body: str) -> None:
    """Reject the PR body if any AI watermark pattern is found."""
    hits: list[str] = []
    for pattern in AI_WATERMARK_PATTERNS:
        if re.search(pattern, body):
            hits.append(pattern)
    if hits:
        die(
            "PR body contains AI-tool watermark(s)."
            " Please remove them before submitting.\n"
            "  Detected patterns:\n    "
            + "\n    ".join(hits)
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

HELP_TEXT = """\
usage: pr_body_structure.py [--config CONFIG] [BODY_TEXT]

Validate that a PR body conforms to the required structure.

Positional arguments:
  BODY_TEXT          PR body text to validate (reads from stdin if omitted).

Options:
  --config CONFIG    Path to a JSON config file that specifies custom
                     required sections.  Expected format:

                      {{ "sections": ["## Summary", "## Test plan", ...] }}

                 Also accepted per section:
                   Summary:           <!-- dayu-harness:summary -->
                   Implementation:    <!-- dayu-harness:implementation-notes -->
                   Test plan:         <!-- dayu-harness:test-plan -->

                     When omitted the default sections are used:
                       {DEFAULT}

  --help             Show this help message and exit.

  --repo OWNER/REPO  Repository used to query open PR bodies for issue-first
                     closing-keyword safety. Defaults to GITHUB_REPOSITORY.

  --pr-number N      Current PR number to exclude from open-PR checks.

  --open-prs-json P  Optional JSON fixture for open PR bodies; primarily used
                     by tests. Expected root object: {{ "pulls": [...] }}.

Exit status:
  0   PR body is valid.
  1   PR body failed one or more checks (details are printed to stderr).
""".format(DEFAULT=", ".join(DEFAULT_SECTIONS))


def parse_args(argv: list[str]) -> tuple[Optional[str], Optional[str], Optional[str], Optional[int], Optional[str]]:
    """Return body, config path, repo, pr number, and open PR fixture path."""
    config: Optional[str] = None
    body: Optional[str] = None
    repo: Optional[str] = None
    pr_number: Optional[int] = None
    open_prs_json: Optional[str] = None
    args = argv[1:]  # skip program name
    i = 0
    while i < len(args):
        if args[i] == "--help":
            print(HELP_TEXT)
            raise SystemExit(0)
        elif args[i] == "--config":
            i += 1
            if i >= len(args):
                die("--config requires a path argument.")
            config = args[i]
        elif args[i] == "--repo":
            i += 1
            if i >= len(args):
                die("--repo requires OWNER/REPO.")
            repo = args[i]
        elif args[i] == "--pr-number":
            i += 1
            if i >= len(args):
                die("--pr-number requires an integer.")
            if not args[i].isdigit():
                die("--pr-number requires an integer.")
            pr_number = int(args[i])
        elif args[i] == "--open-prs-json":
            i += 1
            if i >= len(args):
                die("--open-prs-json requires a path.")
            open_prs_json = args[i]
        elif not args[i].startswith("-"):
            body = args[i]
        else:
            die(f"Unknown option: {args[i]}")
        i += 1
    return body, config, repo, pr_number, open_prs_json


def main() -> None:
    body_arg, config_path, repo, pr_number, open_prs_json = parse_args(sys.argv)

    # Resolve body text.
    if body_arg is not None:
        body = body_arg
    else:
        body = gather_body()

    body = body.strip()
    if not body:
        die("PR body is empty.  A non-empty body is required.")

    # Resolve required sections.
    if config_path is not None:
        cfg = load_config(config_path)
        sections: list[str] = cfg.get("sections", DEFAULT_SECTIONS)
        if not isinstance(sections, list) or not all(isinstance(s, str) for s in sections):
            die("Config 'sections' must be a list of strings.")
    else:
        sections = DEFAULT_SECTIONS

    # Run checks.
    check_sections(body, sections)
    if repo is None:
        repo = os.environ.get("GITHUB_REPOSITORY")
    if pr_number is None:
        raw_pr_number = os.environ.get("PR_NUMBER") or os.environ.get("GITHUB_PR_NUMBER")
        if raw_pr_number and raw_pr_number.isdigit():
            pr_number = int(raw_pr_number)
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")

    check_closing_trailer(body, repo=repo, pr_number=pr_number, token=token, open_prs_json=open_prs_json)
    check_test_plan(body)
    check_watermarks(body)

    print("OK: PR body passes all structure checks.")
    raise SystemExit(0)


if __name__ == "__main__":
    main()
